### ISSUE TITLE
ignore_paths not working

### ISSUE THREAD

**Issue by jensendw** [vito/git-branch-heads-resource#3]
It seems that when I use the git-branch-heads the ignore_paths config parameter does not work.  I tested a similar configuration but using the standard git resource type where it accurately ignored the paths provided.

Incase it helps, this is the pipeline configuration that isn't working:
https://github.com/jensendw/concoursetest/blob/master/ci/pipeline.yml

This is the pipeline configuration that worked:
https://github.com/jensendw/concoursetest/blob/master/ci/pipeline.yml_git_ignore_works

Any help would be much appreciated.

**Comment by vito** [comment]
Hmm this would be kind of a pain to implement. It'd make `check` very expensive; it'd have to fetch every branch rather than just doing `git ls-remote`.

**Comment by JohannesRudolph** [comment]
I think it may be best if `git-branch-heads` would error in case a user sets `paths` or `ignore_paths`. It's all too easy to use `git-branch-heads-resource` as an "upgraded" replacement of `git-resource` and forget about this. 

On the other hand, I wonder how bad the performance impact would be to properly implement paths/ignore_paths since concourse reuses check containers when possible? Would love to hear your thoughts on this @vito. Coming to think of this, once ignore_paths/paths is implemented in `git-branch-heads-resource`, it actually becomes a true superset of `git-resource`, right? Potentially a good idea to upstream the improved version then.

**Comment by vito** [comment]
Closing all these issues and deprecating the repo; concourse/concourse#1707 should remove the need for this resource type entirely.
